package algonquin.cst2335.cst2355final.yuxing;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;


/**
 * SearchTerm represents a search term with its definition and timestamp.
 * <p>
 * This class is used to store information about a search term, including the term itself,
 * its definition, and the timestamp when the search was performed.
 * <p>
 * The class is annotated with Room annotations (@Entity) to specify the database table name
 * and column information for Room database operations.
 *
 */
@Entity(tableName = "search_terms")
public class SearchTerm {
    // Primary key auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    long id;

    // The search term
    @ColumnInfo(name = "term")
    protected String term;

    // The definition of the search term
    @ColumnInfo(name = "definition")
    protected String definition;

    // The timestamp when the search term was sent
    @ColumnInfo(name = "timeSent")
    protected String timeSent;

    /**
     * Default constructor for Room database operations.
     */
    public SearchTerm() {
    }

    /**
     * Constructor to create a new SearchTerm.
     *
     * @param term       The search term.
     * @param timeSent   The timestamp when the search term was sent.
     * @param definition The definition of the search term.
     */
    public SearchTerm(String term, String timeSent, String definition) {
        this.term = term;
        this.timeSent = timeSent;
        this.definition = definition;
    }

    /**
     * Get the search term.
     *
     * @return The search term.
     */
    public String getTerm() {
        return term;
    }

    /**
     * Get the definition of the search term.
     *
     * @return The definition of the search term.
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Get the timestamp when the search term was sent.
     *
     * @return The timestamp when the search term was sent.
     */
    public String getTimeSent() {
        return timeSent;
    }
}


