package algonquin.cst2335.cst2355final.ziyao;import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;


/**
 * Represents a recipe entity for storage in a Room Database.
 *
 * Each instance of this class corresponds to a row in the "Recipe" table.
 */
@Entity
public class Recipe {

    /**
     * Primary key for the recipe, automatically generated by the database.
     */
    @PrimaryKey(autoGenerate=true)
    @ColumnInfo(name="id")
    public int id;

    /**
     * Title of the recipe.
     */
    @ColumnInfo(name="Title")
    protected String title;

    /**
     * Image associated with the recipe.
     */
    @ColumnInfo(name="Image")
    protected String image;

    /**
     * ID associated with the website from which the recipe originates.
     */
    @ColumnInfo(name="websiteID")
    protected int websiteID;


    /**
     * Constructs a Recipe object with the specified title, image, and website ID.
     *
     * @param title The title of the recipe.
     * @param image The image associated with the recipe.
     * @param websiteID The ID associated with the website from which the recipe originates.
     */
    public Recipe(String title, String image, int websiteID)
    {
        this.title = title;
        this.image = image;
        this.websiteID = websiteID;
    }


    /**
     * Gets the title of the recipe.
     *
     * @return The title of the recipe.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Gets the image associated with the recipe.
     *
     * @return The image associated with the recipe.
     */
    public String getImage(){
        return image;
    }

    /**
     * Gets the ID associated with the website from which the recipe originates.
     *
     * @return The website ID.
     */
    public int getWebsiteID(){
        return websiteID;
    }
}